<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Detail_Peminjaman_model extends CI_Model
{

    public $table = 'd_peminjaman';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('d_peminjaman.*, divisi.nama,karyawan.nama_depan,karyawan.nama_belakang');
        $this->db->join('peminjaman', 'd_peminjaman.id_peminjaman = peminjaman.id', 'inner');
        $this->db->join('divisi', 'd_peminjaman.flag=divisi.flag', 'inner');
        $this->db->join('karyawan', 'd_peminjaman.id_karyawan=karyawan.id', 'left');
        $this->db->where('id_peminjaman', $id);
        return $this->db->get($this->table)->result();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('nama', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($idP,$flag, $data)
    {
        $this->db->where('id_peminjaman', $idP);
        $this->db->where('flag', $flag);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Divisi_model.php */
/* Location: ./application/models/Divisi_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-27 08:12:56 */
/* http://harviacode.com */