<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Kendaraan_model extends CI_Model
{

    public $table = 'kendaraan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('no_polisi', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('warna', $q);
        $this->db->or_like('foto', $q);
        $this->db->or_like('status', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('no_polisi', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('warna', $q);
        $this->db->or_like('foto', $q);
        $this->db->or_like('status', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    function get_available()
    {
        $this->db->where('status','0');
        return $this->db->get($this->table)->result();
    }

    function get_count_available()
    {
        $query = $this->db->query(" SELECT	* 
                                    FROM    kendaraan
                                    WHERE	status = '0'");
        $hasil = $query->num_rows();
        return $hasil;
    }

    function get_update_status($id){
        return $this->db->query("UPDATE kendaraan SET status = '0' WHERE id = ".$id."");
    }

}

/* End of file Kendaraan_model.php */
/* Location: ./application/models/Kendaraan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-12-11 09:03:08 */
/* http://harviacode.com */